# Generated by Django 3.2.7 on 2021-09-13 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_service', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Reminders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255, unique=True)),
                ('reminders_user', models.TextField(blank=True)),
                ('date_user', models.DateField()),
                ('time_user', models.TimeField()),
                ('service', models.ManyToManyField(blank=True, to='liff.Service')),
            ],
        ),
    ]
