# Generated by Django 3.2.7 on 2022-09-10 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liff', '0002_remindersdrug_timedrug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminders',
            name='user_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='remindersdrug',
            name='user_id',
            field=models.CharField(max_length=255),
        ),
    ]
